{{- if and .Values.webAdmin.enabled .Values.webAdmin.auth.create (not .Values.webAdmin.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "curvine.webAdminSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "curvine.webAdminLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.webAdmin.auth.usernameKey }}: {{ .Values.webAdmin.auth.username | quote }}
  {{ .Values.webAdmin.auth.passwordKey }}: {{ .Values.webAdmin.auth.password | quote }}
{{- end }}
